from robot_interface import *

# start()
# follow_line_until_intersection()
# grab_cup()
# follow_line_until_intersection()
# slowdown()
# turn_right()
# follow_line_until_intersection()
# slowdown()
# turn_around()
# dance()
# follow_line_until_intersection()
# slowdown()
# turn_right()
# follow_line_until_intersection()
# slowdown()
# turn_left()
# follow_line_until_intersection()
# slowdown()
# turn_around()
# drop_cup()
# follow_line_until_intersection()
# slowdown()
# turn_right()
# follow_line_until_intersection()
# slowdown()
# end()
follow_line_until_intersection()
grab_cup()
turn_left()
follow_line_until_intersection()
get_drink_A()
follow_line_until_intersection(slow = True, slow_duration = 500)
follow_line_until_intersection()
get_drink_B()
follow_line_until_intersection(slow=True)
turn_right()
robot.straight_line_moving(duration = 2000)
time.sleep(2)
drop_cup()