from robot_interface import *

# start()
# follow_line_until_intersection()
# grab_cup()
# follow_line_until_intersection()
# slowdown()
# turn_right()
# follow_line_until_intersection()
# slowdown()
# turn_around()
# dance()
# follow_line_until_intersection()
# slowdown()
# turn_right()
# follow_line_until_intersection()
# slowdown()
# turn_left()
# follow_line_until_intersection()
# slowdown()
# turn_around()
# drop_cup()
# follow_line_until_intersection()
# slowdown()
# turn_right()
# follow_line_until_intersection()
# slowdown()
# end()
follow_line_until_intersection()
grab_cup()
go_to_first_drink()
time.sleep(2)
go_to_second_drink()
time.sleep(10)
back_to_track()
robot.straight_line_moving(duration = 2000)
time.sleep(2)
drop_cup()