from robot_interface import *

# start()
# follow_line_until_intersection()
# grab_cup()
# follow_line_until_intersection()
# slowdown()
# turn_right()
# follow_line_until_intersection()
# slowdown()
# turn_around()
# dance()
# follow_line_until_intersection()
# slowdown()
# turn_right()
# follow_line_until_intersection()
# slowdown()
# turn_left()
# follow_line_until_intersection()
# slowdown()
# turn_around()
# drop_cup()
# follow_line_until_intersection()
# slowdown()
# turn_right()
# follow_line_until_intersection()
# slowdown()
# end()

follow_line_until_intersection()
turn_right()
wait_for_drink()
time.sleep(2)
drink_received()
turn_right()
turn_right()
wait_for_drink()
time.sleep(2)
drink_received()
turn_left()
end()
