from robot_interface import *

start()
follow_line_until_intersection()
grab_cup()
follow_line_until_intersection()
slowdown()
turn_right()
follow_line_until_intersection()
slowdown()
turn_around()
dance()
follow_line_until_intersection()
slowdown()
turn_left()
drop_cup()
end()